@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin

User -> (登录)
Admin -> (登入)
(登入) -> (用户管理)
(登入) -> (歌曲管理)
(删除用户) .. (用户管理)
(增加用户) .. (用户管理)
(增加歌曲) .. (歌曲管理)
(删除歌曲) .. (歌曲管理)
(增加歌手) .. (歌曲管理)
(删除歌手) .. (歌曲管理)
(增加歌单) .. (歌曲管理)
(删除歌单) .. (歌曲管理)

(搜索歌手或歌单或歌曲) -> (启动音乐播放器)
(登录) -> (搜索歌手或歌单或歌曲)
(登录) -> (修改个人资料)
(修改头像) .. (修改个人资料)
(修改生日) .. (修改个人资料)
(修改性别) .. (修改个人资料)
(音乐播放) .. (启动音乐播放器)
(音乐暂停) .. (启动音乐播放器)
(音乐停止) .. (启动音乐播放器)





@enduml